import { STATES_DATA } from '../';

it('should have 56 States and Congressional Districts', () => {
  expect(STATES_DATA.length).toEqual(56);
});

it('should have the appropriate number of EVs for each State and Congressional District', () => {
  expect(STATES_DATA[0].name).toEqual('Alabama');
  expect(STATES_DATA[0].evs).toEqual(9);
  expect(STATES_DATA[1].name).toEqual('Alaska');
  expect(STATES_DATA[1].evs).toEqual(3);
  expect(STATES_DATA[2].name).toEqual('Arizona');
  expect(STATES_DATA[2].evs).toEqual(11);
  expect(STATES_DATA[3].name).toEqual('Arkansas');
  expect(STATES_DATA[3].evs).toEqual(6);
  expect(STATES_DATA[4].name).toEqual('California');
  expect(STATES_DATA[4].evs).toEqual(54);
  expect(STATES_DATA[5].name).toEqual('Colorado');
  expect(STATES_DATA[5].evs).toEqual(10);
  expect(STATES_DATA[6].name).toEqual('Connecticut');
  expect(STATES_DATA[6].evs).toEqual(7);
  expect(STATES_DATA[7].name).toEqual('Delaware');
  expect(STATES_DATA[7].evs).toEqual(3);
  expect(STATES_DATA[8].name).toEqual('Florida');
  expect(STATES_DATA[8].evs).toEqual(30);
  expect(STATES_DATA[9].name).toEqual('Georgia');
  expect(STATES_DATA[9].evs).toEqual(16);
  expect(STATES_DATA[10].name).toEqual('Hawaii');
  expect(STATES_DATA[10].evs).toEqual(4);
  expect(STATES_DATA[11].name).toEqual('Idaho');
  expect(STATES_DATA[11].evs).toEqual(4);
  expect(STATES_DATA[12].name).toEqual('Illinois');
  expect(STATES_DATA[12].evs).toEqual(19);
  expect(STATES_DATA[13].name).toEqual('Indiana');
  expect(STATES_DATA[13].evs).toEqual(11);
  expect(STATES_DATA[14].name).toEqual('Iowa');
  expect(STATES_DATA[14].evs).toEqual(6);
  expect(STATES_DATA[15].name).toEqual('Kansas');
  expect(STATES_DATA[15].evs).toEqual(6);
  expect(STATES_DATA[16].name).toEqual('Kentucky');
  expect(STATES_DATA[16].evs).toEqual(8);
  expect(STATES_DATA[17].name).toEqual('Louisiana');
  expect(STATES_DATA[17].evs).toEqual(8);
  expect(STATES_DATA[18].name).toEqual('ME-CD1');
  expect(STATES_DATA[18].evs).toEqual(1);
  expect(STATES_DATA[19].name).toEqual('ME-CD2');
  expect(STATES_DATA[19].evs).toEqual(1);
  expect(STATES_DATA[20].name).toEqual('Maine');
  expect(STATES_DATA[20].evs).toEqual(2);
  expect(STATES_DATA[21].name).toEqual('Maryland');
  expect(STATES_DATA[21].evs).toEqual(10);
  expect(STATES_DATA[22].name).toEqual('Massachusetts');
  expect(STATES_DATA[22].evs).toEqual(11);
  expect(STATES_DATA[23].name).toEqual('Michigan');
  expect(STATES_DATA[23].evs).toEqual(15);
  expect(STATES_DATA[24].name).toEqual('Minnesota');
  expect(STATES_DATA[24].evs).toEqual(10);
  expect(STATES_DATA[25].name).toEqual('Mississippi');
  expect(STATES_DATA[25].evs).toEqual(6);
  expect(STATES_DATA[26].name).toEqual('Missouri');
  expect(STATES_DATA[26].evs).toEqual(10);
  expect(STATES_DATA[27].name).toEqual('Montana');
  expect(STATES_DATA[27].evs).toEqual(4);
  expect(STATES_DATA[28].name).toEqual('NE-CD1');
  expect(STATES_DATA[28].evs).toEqual(1);
  expect(STATES_DATA[29].name).toEqual('NE-CD2');
  expect(STATES_DATA[29].evs).toEqual(1);
  expect(STATES_DATA[30].name).toEqual('NE-CD3');
  expect(STATES_DATA[30].evs).toEqual(1);
  expect(STATES_DATA[31].name).toEqual('Nebraska');
  expect(STATES_DATA[31].evs).toEqual(2);
  expect(STATES_DATA[32].name).toEqual('Nevada');
  expect(STATES_DATA[32].evs).toEqual(6);
  expect(STATES_DATA[33].name).toEqual('New Hampshire');
  expect(STATES_DATA[33].evs).toEqual(4);
  expect(STATES_DATA[34].name).toEqual('New Jersey');
  expect(STATES_DATA[34].evs).toEqual(14);
  expect(STATES_DATA[35].name).toEqual('New Mexico');
  expect(STATES_DATA[35].evs).toEqual(5);
  expect(STATES_DATA[36].name).toEqual('New York');
  expect(STATES_DATA[36].evs).toEqual(28);
  expect(STATES_DATA[37].name).toEqual('North Carolina');
  expect(STATES_DATA[37].evs).toEqual(16);
  expect(STATES_DATA[38].name).toEqual('North Dakota');
  expect(STATES_DATA[38].evs).toEqual(3);
  expect(STATES_DATA[39].name).toEqual('Ohio');
  expect(STATES_DATA[39].evs).toEqual(17);
  expect(STATES_DATA[40].name).toEqual('Oklahoma');
  expect(STATES_DATA[40].evs).toEqual(7);
  expect(STATES_DATA[41].name).toEqual('Oregon');
  expect(STATES_DATA[41].evs).toEqual(8);
  expect(STATES_DATA[42].name).toEqual('Pennsylvania');
  expect(STATES_DATA[42].evs).toEqual(19);
  expect(STATES_DATA[43].name).toEqual('Rhode Island');
  expect(STATES_DATA[43].evs).toEqual(4);
  expect(STATES_DATA[44].name).toEqual('South Carolina');
  expect(STATES_DATA[44].evs).toEqual(9);
  expect(STATES_DATA[45].name).toEqual('South Dakota');
  expect(STATES_DATA[45].evs).toEqual(3);
  expect(STATES_DATA[46].name).toEqual('Tennessee');
  expect(STATES_DATA[46].evs).toEqual(11);
  expect(STATES_DATA[47].name).toEqual('Texas');
  expect(STATES_DATA[47].evs).toEqual(40);
  expect(STATES_DATA[48].name).toEqual('Utah');
  expect(STATES_DATA[48].evs).toEqual(6);
  expect(STATES_DATA[49].name).toEqual('Vermont');
  expect(STATES_DATA[49].evs).toEqual(3);
  expect(STATES_DATA[50].name).toEqual('Virginia');
  expect(STATES_DATA[50].evs).toEqual(13);
  expect(STATES_DATA[51].name).toEqual('Washington');
  expect(STATES_DATA[51].evs).toEqual(12);
  expect(STATES_DATA[52].name).toEqual('Washington, D.C.');
  expect(STATES_DATA[52].evs).toEqual(3);
  expect(STATES_DATA[53].name).toEqual('West Virginia');
  expect(STATES_DATA[53].evs).toEqual(4);
  expect(STATES_DATA[54].name).toEqual('Wisconsin');
  expect(STATES_DATA[54].evs).toEqual(10);
  expect(STATES_DATA[55].name).toEqual('Wyoming');
  expect(STATES_DATA[55].evs).toEqual(3);
});

it('should have stateEvs only for Maine and Nebraska', () => {
  expect(STATES_DATA[20].stateEvs).toEqual(4);
  expect(STATES_DATA[31].stateEvs).toEqual(5);
  expect(STATES_DATA[0].stateEvs).toBe(undefined);
});
